Set `project.originalModel` after flattening
mojohaus/flatten-maven-plugin pull request #281
Opened 2022-05-31 15:34 UTC by clayreimann

Based on the discussion in https://github.com/apache/maven-shade-plugin/pull/129#discussion_r843695691 It seems that the flatten plugin should update the `originalModel` property after we flatten the pom.

This issue resolves #100 and is an alternate way to close #279

2022-06-02 18:11 UTC, clayreimann commented
@slachiewicz I know you may be busy, but do you have initial thoughts on this PR?

2022-06-30 16:52 UTC, clayreimann commented
@slachiewicz any update on this?

2022-07-11 15:11 UTC, clayreimann commented
@slachiewicz more ping. If you're busy, or not much involved any more, can you recommend someone else who might review?

2022-08-07 14:03 UTC, slawekjaranowski commented
Please squash to one final commit

2022-08-07 23:30 UTC, slawekjaranowski requested changes

2022-08-07 23:30 UTC, slawekjaranowski commented on README.md
> +  `<projectsDirectory>` path of the `run-its` profile to point to the directory containing your single test case.
We can use: `invoker.test` property

```
mvn verify -P run-its -Dinvoker.test=<projectsDirectory>
```

2022-08-07 23:30 UTC, slawekjaranowski commented on pom.xml
> +              <streamLogsOnFailures>true</streamLogsOnFailures>
no need - present in parent ...

2022-08-07 23:30 UTC, slawekjaranowski commented on src/it/projects/flatten-shaded-drp/invoker.properties
> +invoker.goals=package
missing new line

2022-08-07 23:30 UTC, slawekjaranowski commented on src/it/projects/flatten-shaded-drp/pom.xml
> +    </properties>
two space indents

2022-08-15 13:10 UTC, slawekjaranowski approved these changes

2022-08-15 13:11 UTC, merged

2022-08-15 20:18 UTC, mkarg commented
Thanks for fixing this issue! :-)