Feature/extended interpolate
mojohaus/flatten-maven-plugin pull request #384
Opened 2023-11-21 16:04 UTC by SergeDemoulinGebit

new ElementHandling: "extended_interpolate"

- Take the element from the interpolated POM, but resolve the variables with the properties from the effective POM.
- Don't resolve the following variables "project.basedir", "project.baseUri", "project.build.directory", "project.build.outputDirectory", "project.build.sourceDirectory", "project.build.scriptSourceDirectory", "project.build.testSourceDirectory", "project.reporting.outputDirectory"
- Interpolate the parent version

Optimization (only the used models are created)

2023-11-21 16:10 UTC, SergeDemoulinGebit commented
resolve #383 resolve #382

2024-01-09 08:23 UTC, slawekjaranowski commented
Please don't change line end and other whitespace

2024-03-12 11:35 UTC, SergeDemoulinGebit commented
Hi
I fix the line ends now. 
Sorry for the late answer, I did not see the comment. This feature is important for us and very useful.

I want to remove the dependency to guava. Please wait until I do that to make the review.

Best regards,
Serge

2024-03-24 23:32 UTC, kjq commented
This would be huge for us because we have a lot of properties in a parent that need to be interpolated in lower POMs.

2024-05-08 08:56 UTC, cpfeiffer commented
Is there anything we can do to move this forward?

2024-05-08 16:53 UTC, slawekjaranowski commented
I added myself to review, I will try to do it in a few days - @SergeDemoulinGebit thanks for PR

2024-05-13 17:22 UTC, slawekjaranowski commented on src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
> +    }
This method and corresponding is not needed we have all this values in debug log, executing Maven with -X
like:
```
ehaus.mojo:flatten-maven-plugin:1.6.1-SNAPSHOT:flatten from plugin realm ClassRealm[plugin>org.codehaus.mojo:flatten-maven-plugin:1.6.1-SNAPSHOT, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@63c12fb0]
[DEBUG] Configuring mojo execution 'org.codehaus.mojo:flatten-maven-plugin:1.6.1-SNAPSHOT:flatten:default-cli' with basic configurator -->
[DEBUG]   (f) defaultOperation = flatten
[DEBUG]   (f) embedBuildProfileDependencies = false
[DEBUG]   (f) flattenMode = bom
[DEBUG]   (f) flattenedPomFilename = .flattened-pom.xml
[DEBUG]   (f) keepCommentsInPom = false

```

2024-05-14 07:11 UTC, SergeDemoulinGebit commented
right. I learnt it afterall

2024-05-14 07:52 UTC, slawekjaranowski requested changes

2024-05-14 07:52 UTC, slawekjaranowski commented on src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
> +import java.io.*;
please don't use asterisk in imports

2024-05-14 07:52 UTC, slawekjaranowski commented on src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
> +    private String asString(Map<String, Object> map) {
where is used? and other new methods

2024-09-11 08:41 UTC, cpfeiffer commented
Kind request -- can we move forward with this?

2024-09-13 18:15 UTC, slawekjaranowski approved these changes

2024-09-13 18:16 UTC, merged

2024-09-13 18:17 UTC, slawekjaranowski commented
@SergeDemoulinGebit thanks

2024-09-16 08:38 UTC, cpfeiffer commented
Awesome, thank you so much!

2024-09-16 08:50 UTC, SergeDemoulinGebit commented
Thank you Slawomir 😄
________________________________
From: Slawomir Jaranowski ***@***.***>
Sent: 13 September 2024 20:17
To: mojohaus/flatten-maven-plugin ***@***.***>
Cc: Serge Démoulin ***@***.***>; Mention ***@***.***>
Subject: Re: [mojohaus/flatten-maven-plugin] Feature/extended interpolate (PR #384)


@SergeDemoulinGebit<https://github.com/SergeDemoulinGebit> thanks

—
Reply to this email directly, view it on GitHub<https://github.com/mojohaus/flatten-maven-plugin/pull/384#issuecomment-2349764026>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BAILLUDEAHZWTZDFEPVQIM3ZWMT4TAVCNFSM6AAAAAA7U2QO5GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNBZG43DIMBSGY>.
You are receiving this because you were mentioned.Message ID: ***@***.***>